const defaultNewWordsArray = [
  {
    id: "5e9f5ee35eb9e72bc21af4b4",
    group: 0,
    page: 1,
    word: "adventure",
    image: "files/02_0021.jpg",
    audio: "files/02_0021.mp3",
    audioMeaning: "files/02_0021_meaning.mp3",
    audioExample: "files/02_0021_example.mp3",
    textMeaning: "An <i>adventure</i> is a fun or exciting thing that you do.",
    textExample: "Riding in the rough water was an <b>adventure</b>.",
    transcription: "[ədvéntʃər]",
    textExampleTranslate: "Езда в бурной воде была приключением",
    textMeaningTranslate: "Приключение - это забавная или захватывающая вещь, которую ты делаешь",
    wordTranslate: "приключение",
    wordsPerExampleSentence: 8,
  },
  {
    id: "5e9f5ee35eb9e72bc21af4b5",
    group: 0,
    page: 1,
    word: "approach",
    image: "files/02_0022.jpg",
    audio: "files/02_0022.mp3",
    audioMeaning: "files/02_0022_meaning.mp3",
    audioExample: "files/02_0022_example.mp3",
    textMeaning: "To <i>approach</i> something means to move close to it.",
    textExample: "The boy <b>approached</b> his school.",
    transcription: "[əpróutʃ]",
    textExampleTranslate: "Мальчик приблизился к своей школе",
    textMeaningTranslate: "Подойти к чему-то - значит приблизиться к нему",
    wordTranslate: "подходить",
    wordsPerExampleSentence: 5,
  },
  {
    id: "5e9f5ee35eb9e72bc21af4b6",
    group: 0,
    page: 1,
    word: "chemical",
    image: "files/02_0024.jpg",
    audio: "files/02_0024.mp3",
    audioMeaning: "files/02_0024_meaning.mp3",
    audioExample: "files/02_0024_example.mp3",
    textMeaning: "A <i>chemical</i> is something that scientists use in chemistry.",
    textExample: "The scientist mixed the <b>chemicals</b>.",
    transcription: "[kémikəl]",
    textExampleTranslate: "Ученый смешал химикаты",
    textMeaningTranslate: "Химическое вещество - это то, что ученые используют в химии",
    wordTranslate: "химический",
    wordsPerExampleSentence: 5,
  },
  {
    id: "5e9f5ee35eb9e72bc21af4b7",
    group: 0,
    page: 1,
    word: "carefully",
    image: "files/02_0023.jpg",
    audio: "files/02_0023.mp3",
    audioMeaning: "files/02_0023_meaning.mp3",
    audioExample: "files/02_0023_example.mp3",
    textMeaning: "<i>Carefully</i> means with great attention, especially to detail or safety.",
    textExample: "The baby <b>carefully</b> climbed down the stairs.",
    transcription: "[kɛ́ərfəli]",
    textExampleTranslate: "Малыш осторожно спускался по лестнице",
    textMeaningTranslate:
      "Осторожно означает с большим вниманием, особенно к деталям или безопасности",
    wordTranslate: "внимательно",
    wordsPerExampleSentence: 7,
  },
  {
    id: "5e9f5ee35eb9e72bc21af4b8",
    group: 0,
    page: 1,
    word: "create",
    image: "files/02_0025.jpg",
    audio: "files/02_0025.mp3",
    audioMeaning: "files/02_0025_meaning.mp3",
    audioExample: "files/02_0025_example.mp3",
    textMeaning: "To <i>create</i> means to make something new.",
    textExample: "She <b>created</b> an igloo from blocks of snow.",
    transcription: "[kriéit]",
    textExampleTranslate: "Она создала иглу из снежных глыб",
    textMeaningTranslate: "Создать значит создать что-то новое",
    wordTranslate: "создайте",
    wordsPerExampleSentence: 8,
  },
];

export default defaultNewWordsArray;
