export default [
  {
    id: 0,
    name: "Return from the Falcon Hunt",
    imageSrc: "level3/3_01.jpg",
    cutSrc: "level3/cut/3_01.jpg",
    author: "BERCHEM, Nicolaes",
    year: "1650",
  },
  {
    id: 1,
    name: "Rocky Landscape with Antique Ruins",
    imageSrc: "level3/3_02.jpg",
    cutSrc: "level3/cut/3_02.jpg",
    author: "BERCHEM, Nicolaes",
    year: "1657",
  },
  {
    id: 2,
    name: "The Banks of the Manzanares River",
    imageSrc: "level3/3_03.jpg",
    cutSrc: "level3/cut/3_03.jpg",
    author: "BERUETE, Aureliano",
    year: "1878",
  },
  {
    id: 3,
    name: "The Augustan Bridge",
    imageSrc: "level3/3_04.jpg",
    cutSrc: "level3/cut/3_04.jpg",
    author: "BIDAULD, Jean-Joseph-Xavier",
    year: "1790",
  },
  {
    id: 4,
    name: "Landscape with Sarcophagus",
    imageSrc: "level3/3_05.jpg",
    cutSrc: "level3/cut/3_05.jpg",
    author: "BLANCHET, Thomas",
    year: "1650-1652",
  },
  {
    id: 5,
    name: "Building the Devil's Bridge",
    imageSrc: "level3/3_06.jpg",
    cutSrc: "level3/cut/3_06.jpg",
    author: "BLECHEN, Karl",
    year: "1833",
  },
  {
    id: 6,
    name: "Stag Hunting in the Dunes",
    imageSrc: "level3/3_07.jpg",
    cutSrc: "level3/cut/3_07.jpg",
    author: "BLEKER, Gerrit Claesz",
    year: "1625-1629",
  },
  {
    id: 7,
    name: "Landscape with the Prophet Elijah in the Desert",
    imageSrc: "level3/3_08.jpg",
    cutSrc: "level3/cut/3_08.jpg",
    author: "BLOEMAERT, Abraham",
    year: "1610",
  },
  {
    id: 8,
    name: "River Landscape with a Town and Fortified Tower",
    imageSrc: "level3/3_09.jpg",
    cutSrc: "level3/cut/3_09.jpg",
    author: "GOYEN, Jan van",
    year: "1633",
  },
  {
    id: 9,
    name: "The Champion Single Sculls (Max Schmitt in a Single Scull)",
    imageSrc: "level3/3_10.jpg",
    cutSrc: "level3/cut/3_10.jpg",
    author: "EAKINS, Thomas",
    year: "1871",
  },
  {
    id: 10,
    name: "A Frigate, Calm Seas",
    imageSrc: "level3/3_11.jpg",
    cutSrc: "level3/cut/3_11.jpg",
    author: "ECKARDT, Christian Frederik Emil",
    year: "1867",
  },
  {
    id: 11,
    name: "A Brig under Sail in Fair Weather",
    imageSrc: "level3/3_12.jpg",
    cutSrc: "level3/cut/3_12.jpg",
    author: "ECKERSBERG, Christoffer Wilhelm",
    year: "1844-1845",
  },
  {
    id: 12,
    name: "The Cloisters, San Lorenzo fuori le mura",
    imageSrc: "level3/3_13.jpg",
    cutSrc: "level3/cut/3_13.jpg",
    author: "ECKERSBERG, Christoffer Wilhelm",
    year: "1824",
  },
  {
    id: 13,
    name: "View of Amsterdam",
    imageSrc: "level3/3_14.jpg",
    cutSrc: "level3/cut/3_14.jpg",
    author: "EKELS, Jan the Elder",
    year: "1750-1780",
  },
  {
    id: 14,
    name: "View of the Zuidsingel, Amersfoort",
    imageSrc: "level3/3_15.jpg",
    cutSrc: "level3/cut/3_15.jpg",
    author: "EKELS, Jan the Elder",
    year: "1760-1780",
  },
  {
    id: 15,
    name: "Seascape",
    imageSrc: "level3/3_16.jpg",
    cutSrc: "level3/cut/3_16.jpg",
    author: "EYCK, Gaspard van",
    year: "1650",
  },
  {
    id: 16,
    name: "Southern Pastoral",
    imageSrc: "level3/3_17.jpg",
    cutSrc: "level3/cut/3_17.jpg",
    author: "BERCHEM, Nicolaes",
    year: "1658",
  },
  {
    id: 17,
    name: "Winter Landscape",
    imageSrc: "level3/3_18.jpg",
    cutSrc: "level3/cut/3_18.jpg",
    author: "BERGHE, Christoffel van den",
    year: "1615-1620",
  },
  {
    id: 18,
    name: "The Silver Seascape",
    imageSrc: "level3/3_19.jpg",
    cutSrc: "level3/cut/3_19.jpg",
    author: "BEYEREN, Abraham van",
    year: "1640-1650",
  },
  {
    id: 19,
    name: "View of the Isle of Sora",
    imageSrc: "level3/3_20.jpg",
    cutSrc: "level3/cut/3_20.jpg",
    author: "BIDAULD, Jean-Joseph-Xavier",
    year: "1793",
  },
  {
    id: 20,
    name: "Cavalry Battle Scene",
    imageSrc: "level3/3_21.jpg",
    cutSrc: "level3/cut/3_21.jpg",
    author: "BLEKER, Gerrit Claesz",
    year: "1656",
  },
  {
    id: 21,
    name: "Landscape with the Parable of the Tares among the Wheat",
    imageSrc: "level3/3_22.jpg",
    cutSrc: "level3/cut/3_22.jpg",
    author: "BLOEMAERT, Abraham",
    year: "1624",
  },
  {
    id: 22,
    name: "A Scene in the Roman Campagna",
    imageSrc: "level3/3_23.jpg",
    cutSrc: "level3/cut/3_23.jpg",
    author: "BLOEMEN, Jan Frans van",
    year: "1736",
  },
  {
    id: 23,
    name: "Naples, a View of Mergellina",
    imageSrc: "level3/3_24.jpg",
    cutSrc: "level3/cut/3_24.jpg",
    author: "BLOEMEN, Jan Frans van",
    year: "1777",
  },
  {
    id: 24,
    name: "River Landscape",
    imageSrc: "level3/3_25.jpg",
    cutSrc: "level3/cut/3_25.jpg",
    author: "GAINSBOROUGH, Thomas",
    year: "1768-1770",
  },
  {
    id: 25,
    name: "The Seine in Paris between the Pont d'Iéna and Pont de Grenelle",
    imageSrc: "level3/3_26.jpg",
    cutSrc: "level3/cut/3_26.jpg",
    author: "GAUGUIN, Paul",
    year: "1875",
  },
  {
    id: 26,
    name: "A Corroboree in Van Diemen's Land",
    imageSrc: "level3/3_27.jpg",
    cutSrc: "level3/cut/3_27.jpg",
    author: "GLOVER, John",
    year: "1840",
  },
  {
    id: 27,
    name: "Beach at Scheveningen in Stormy Weather",
    imageSrc: "level3/3_28.jpg",
    cutSrc: "level3/cut/3_28.jpg",
    author: "GOGH, Vincent van",
    year: "1882",
  },
  {
    id: 28,
    name: "Farmhouses among Trees",
    imageSrc: "level3/3_29.jpg",
    cutSrc: "level3/cut/3_29.jpg",
    author: "GOGH, Vincent van",
    year: "1883",
  },
  {
    id: 29,
    name: "Two Peasant Women in the Peat Field",
    imageSrc: "level3/3_30.jpg",
    cutSrc: "level3/cut/3_30.jpg",
    author: "GOGH, Vincent van",
    year: "1883",
  },
  {
    id: 30,
    name: "The Parsonage Garden at Nuenen in Spring",
    imageSrc: "level3/3_31.jpg",
    cutSrc: "level3/cut/3_31.jpg",
    author: "GOGH, Vincent van",
    year: "1884",
  },
  {
    id: 31,
    name: "In the Jardin du Luxembourg",
    imageSrc: "level3/3_32.jpg",
    cutSrc: "level3/cut/3_32.jpg",
    author: "GOGH, Vincent van",
    year: "1886",
  },
  {
    id: 32,
    name: "View of Paris from Montmartre",
    imageSrc: "level3/3_33.jpg",
    cutSrc: "level3/cut/3_33.jpg",
    author: "GOGH, Vincent van",
    year: "1886",
  },
  {
    id: 33,
    name: "Olive Picking",
    imageSrc: "level3/3_34.jpg",
    cutSrc: "level3/cut/3_34.jpg",
    author: "GOGH, Vincent van",
    year: "1889",
  },
  {
    id: 34,
    name: "Landscape with Carriage and Train in the Background",
    imageSrc: "level3/3_35.jpg",
    cutSrc: "level3/cut/3_35.jpg",
    author: "GOGH, Vincent van",
    year: "1890",
  },
  {
    id: 35,
    name: "Wheat Field under Clouded Sky",
    imageSrc: "level3/3_36.jpg",
    cutSrc: "level3/cut/3_36.jpg",
    author: "GOGH, Vincent van",
    year: "1890",
  },
  {
    id: 36,
    name: "Wheat Field with Crows",
    imageSrc: "level3/3_37.jpg",
    cutSrc: "level3/cut/3_37.jpg",
    author: "GOGH, Vincent van",
    year: "1890",
  },
  {
    id: 37,
    name: "The Meadow of San Isidro on his Feast Day",
    imageSrc: "level3/3_38.jpg",
    cutSrc: "level3/cut/3_38.jpg",
    author: "GOYA Y LUCIENTES, Francisco de",
    year: "1788",
  },
  {
    id: 38,
    name: "Dune Landscape",
    imageSrc: "level3/3_39.jpg",
    cutSrc: "level3/cut/3_39.jpg",
    author: "GOYEN, Jan van",
    year: "1631",
  },
  {
    id: 39,
    name: "Haymaking",
    imageSrc: "level3/3_40.jpg",
    cutSrc: "level3/cut/3_40.jpg",
    author: "GOYEN, Jan van",
    year: "1630",
  },
];
