export default {
  STEP_SLIDER_CARDS: 5,
  DEFAULT_WORDS_PER_DAY: 30,
  DEFAULT_NEW_WORDS_PER_DAY: 15,
  MIN_WORDS_PER_DAY: 10,
  MAX_WORDS_PER_DAY: 100,
  MIN_NEW_WORDS_PER_DAY: 10,
  MAX_NEW_WORDS_PER_DAY: 90,
};
